(cl:in-package body_tracker_msgs-msg)
(cl:export '(BODY_ID-VAL
          BODY_ID
          TRACKING_STATUS-VAL
          TRACKING_STATUS
          GESTURE-VAL
          GESTURE
          FACE_FOUND-VAL
          FACE_FOUND
          FACE_LEFT-VAL
          FACE_LEFT
          FACE_TOP-VAL
          FACE_TOP
          FACE_WIDTH-VAL
          FACE_WIDTH
          FACE_HEIGHT-VAL
          FACE_HEIGHT
          AGE-VAL
          AGE
          GENDER-VAL
          GENDER
          NAME-VAL
          NAME
          POSITION2D-VAL
          POSITION2D
          POSITION3D-VAL
          POSITION3D
          FACE_CENTER-VAL
          FACE_CENTER
))