# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from body_tracker_msgs/Skeleton.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Skeleton(genpy.Message):
  _md5sum = "3ccf81ce06b8e4b357ba011ca33898c6"
  _type = "body_tracker_msgs/Skeleton"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Header header # I CANT GET THIS TO COMPILE!

int32 body_id
int32 tracking_status
int32 gesture

geometry_msgs/Point32 position2D # x,y in camera frame, z distance from camera

geometry_msgs/Point32 centerOfMass

#Position of interesting joints
geometry_msgs/Point32 joint_position_head
geometry_msgs/Point32 joint_position_neck
geometry_msgs/Point32 joint_position_shoulder
geometry_msgs/Point32 joint_position_spine_top
geometry_msgs/Point32 joint_position_spine_mid
geometry_msgs/Point32 joint_position_spine_bottom

geometry_msgs/Point32 joint_position_left_shoulder
geometry_msgs/Point32 joint_position_left_elbow
geometry_msgs/Point32 joint_position_left_hand

geometry_msgs/Point32 joint_position_right_shoulder
geometry_msgs/Point32 joint_position_right_elbow
geometry_msgs/Point32 joint_position_right_hand

# Robot is usually too close to see legs, and not very interesting



================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z"""
  __slots__ = ['body_id','tracking_status','gesture','position2D','centerOfMass','joint_position_head','joint_position_neck','joint_position_shoulder','joint_position_spine_top','joint_position_spine_mid','joint_position_spine_bottom','joint_position_left_shoulder','joint_position_left_elbow','joint_position_left_hand','joint_position_right_shoulder','joint_position_right_elbow','joint_position_right_hand']
  _slot_types = ['int32','int32','int32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       body_id,tracking_status,gesture,position2D,centerOfMass,joint_position_head,joint_position_neck,joint_position_shoulder,joint_position_spine_top,joint_position_spine_mid,joint_position_spine_bottom,joint_position_left_shoulder,joint_position_left_elbow,joint_position_left_hand,joint_position_right_shoulder,joint_position_right_elbow,joint_position_right_hand

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Skeleton, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.body_id is None:
        self.body_id = 0
      if self.tracking_status is None:
        self.tracking_status = 0
      if self.gesture is None:
        self.gesture = 0
      if self.position2D is None:
        self.position2D = geometry_msgs.msg.Point32()
      if self.centerOfMass is None:
        self.centerOfMass = geometry_msgs.msg.Point32()
      if self.joint_position_head is None:
        self.joint_position_head = geometry_msgs.msg.Point32()
      if self.joint_position_neck is None:
        self.joint_position_neck = geometry_msgs.msg.Point32()
      if self.joint_position_shoulder is None:
        self.joint_position_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_spine_top is None:
        self.joint_position_spine_top = geometry_msgs.msg.Point32()
      if self.joint_position_spine_mid is None:
        self.joint_position_spine_mid = geometry_msgs.msg.Point32()
      if self.joint_position_spine_bottom is None:
        self.joint_position_spine_bottom = geometry_msgs.msg.Point32()
      if self.joint_position_left_shoulder is None:
        self.joint_position_left_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_left_elbow is None:
        self.joint_position_left_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_left_hand is None:
        self.joint_position_left_hand = geometry_msgs.msg.Point32()
      if self.joint_position_right_shoulder is None:
        self.joint_position_right_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_right_elbow is None:
        self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_right_hand is None:
        self.joint_position_right_hand = geometry_msgs.msg.Point32()
    else:
      self.body_id = 0
      self.tracking_status = 0
      self.gesture = 0
      self.position2D = geometry_msgs.msg.Point32()
      self.centerOfMass = geometry_msgs.msg.Point32()
      self.joint_position_head = geometry_msgs.msg.Point32()
      self.joint_position_neck = geometry_msgs.msg.Point32()
      self.joint_position_shoulder = geometry_msgs.msg.Point32()
      self.joint_position_spine_top = geometry_msgs.msg.Point32()
      self.joint_position_spine_mid = geometry_msgs.msg.Point32()
      self.joint_position_spine_bottom = geometry_msgs.msg.Point32()
      self.joint_position_left_shoulder = geometry_msgs.msg.Point32()
      self.joint_position_left_elbow = geometry_msgs.msg.Point32()
      self.joint_position_left_hand = geometry_msgs.msg.Point32()
      self.joint_position_right_shoulder = geometry_msgs.msg.Point32()
      self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      self.joint_position_right_hand = geometry_msgs.msg.Point32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3i42f().pack(_x.body_id, _x.tracking_status, _x.gesture, _x.position2D.x, _x.position2D.y, _x.position2D.z, _x.centerOfMass.x, _x.centerOfMass.y, _x.centerOfMass.z, _x.joint_position_head.x, _x.joint_position_head.y, _x.joint_position_head.z, _x.joint_position_neck.x, _x.joint_position_neck.y, _x.joint_position_neck.z, _x.joint_position_shoulder.x, _x.joint_position_shoulder.y, _x.joint_position_shoulder.z, _x.joint_position_spine_top.x, _x.joint_position_spine_top.y, _x.joint_position_spine_top.z, _x.joint_position_spine_mid.x, _x.joint_position_spine_mid.y, _x.joint_position_spine_mid.z, _x.joint_position_spine_bottom.x, _x.joint_position_spine_bottom.y, _x.joint_position_spine_bottom.z, _x.joint_position_left_shoulder.x, _x.joint_position_left_shoulder.y, _x.joint_position_left_shoulder.z, _x.joint_position_left_elbow.x, _x.joint_position_left_elbow.y, _x.joint_position_left_elbow.z, _x.joint_position_left_hand.x, _x.joint_position_left_hand.y, _x.joint_position_left_hand.z, _x.joint_position_right_shoulder.x, _x.joint_position_right_shoulder.y, _x.joint_position_right_shoulder.z, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_hand.x, _x.joint_position_right_hand.y, _x.joint_position_right_hand.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position2D is None:
        self.position2D = geometry_msgs.msg.Point32()
      if self.centerOfMass is None:
        self.centerOfMass = geometry_msgs.msg.Point32()
      if self.joint_position_head is None:
        self.joint_position_head = geometry_msgs.msg.Point32()
      if self.joint_position_neck is None:
        self.joint_position_neck = geometry_msgs.msg.Point32()
      if self.joint_position_shoulder is None:
        self.joint_position_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_spine_top is None:
        self.joint_position_spine_top = geometry_msgs.msg.Point32()
      if self.joint_position_spine_mid is None:
        self.joint_position_spine_mid = geometry_msgs.msg.Point32()
      if self.joint_position_spine_bottom is None:
        self.joint_position_spine_bottom = geometry_msgs.msg.Point32()
      if self.joint_position_left_shoulder is None:
        self.joint_position_left_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_left_elbow is None:
        self.joint_position_left_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_left_hand is None:
        self.joint_position_left_hand = geometry_msgs.msg.Point32()
      if self.joint_position_right_shoulder is None:
        self.joint_position_right_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_right_elbow is None:
        self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_right_hand is None:
        self.joint_position_right_hand = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 180
      (_x.body_id, _x.tracking_status, _x.gesture, _x.position2D.x, _x.position2D.y, _x.position2D.z, _x.centerOfMass.x, _x.centerOfMass.y, _x.centerOfMass.z, _x.joint_position_head.x, _x.joint_position_head.y, _x.joint_position_head.z, _x.joint_position_neck.x, _x.joint_position_neck.y, _x.joint_position_neck.z, _x.joint_position_shoulder.x, _x.joint_position_shoulder.y, _x.joint_position_shoulder.z, _x.joint_position_spine_top.x, _x.joint_position_spine_top.y, _x.joint_position_spine_top.z, _x.joint_position_spine_mid.x, _x.joint_position_spine_mid.y, _x.joint_position_spine_mid.z, _x.joint_position_spine_bottom.x, _x.joint_position_spine_bottom.y, _x.joint_position_spine_bottom.z, _x.joint_position_left_shoulder.x, _x.joint_position_left_shoulder.y, _x.joint_position_left_shoulder.z, _x.joint_position_left_elbow.x, _x.joint_position_left_elbow.y, _x.joint_position_left_elbow.z, _x.joint_position_left_hand.x, _x.joint_position_left_hand.y, _x.joint_position_left_hand.z, _x.joint_position_right_shoulder.x, _x.joint_position_right_shoulder.y, _x.joint_position_right_shoulder.z, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_hand.x, _x.joint_position_right_hand.y, _x.joint_position_right_hand.z,) = _get_struct_3i42f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3i42f().pack(_x.body_id, _x.tracking_status, _x.gesture, _x.position2D.x, _x.position2D.y, _x.position2D.z, _x.centerOfMass.x, _x.centerOfMass.y, _x.centerOfMass.z, _x.joint_position_head.x, _x.joint_position_head.y, _x.joint_position_head.z, _x.joint_position_neck.x, _x.joint_position_neck.y, _x.joint_position_neck.z, _x.joint_position_shoulder.x, _x.joint_position_shoulder.y, _x.joint_position_shoulder.z, _x.joint_position_spine_top.x, _x.joint_position_spine_top.y, _x.joint_position_spine_top.z, _x.joint_position_spine_mid.x, _x.joint_position_spine_mid.y, _x.joint_position_spine_mid.z, _x.joint_position_spine_bottom.x, _x.joint_position_spine_bottom.y, _x.joint_position_spine_bottom.z, _x.joint_position_left_shoulder.x, _x.joint_position_left_shoulder.y, _x.joint_position_left_shoulder.z, _x.joint_position_left_elbow.x, _x.joint_position_left_elbow.y, _x.joint_position_left_elbow.z, _x.joint_position_left_hand.x, _x.joint_position_left_hand.y, _x.joint_position_left_hand.z, _x.joint_position_right_shoulder.x, _x.joint_position_right_shoulder.y, _x.joint_position_right_shoulder.z, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_hand.x, _x.joint_position_right_hand.y, _x.joint_position_right_hand.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position2D is None:
        self.position2D = geometry_msgs.msg.Point32()
      if self.centerOfMass is None:
        self.centerOfMass = geometry_msgs.msg.Point32()
      if self.joint_position_head is None:
        self.joint_position_head = geometry_msgs.msg.Point32()
      if self.joint_position_neck is None:
        self.joint_position_neck = geometry_msgs.msg.Point32()
      if self.joint_position_shoulder is None:
        self.joint_position_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_spine_top is None:
        self.joint_position_spine_top = geometry_msgs.msg.Point32()
      if self.joint_position_spine_mid is None:
        self.joint_position_spine_mid = geometry_msgs.msg.Point32()
      if self.joint_position_spine_bottom is None:
        self.joint_position_spine_bottom = geometry_msgs.msg.Point32()
      if self.joint_position_left_shoulder is None:
        self.joint_position_left_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_left_elbow is None:
        self.joint_position_left_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_left_hand is None:
        self.joint_position_left_hand = geometry_msgs.msg.Point32()
      if self.joint_position_right_shoulder is None:
        self.joint_position_right_shoulder = geometry_msgs.msg.Point32()
      if self.joint_position_right_elbow is None:
        self.joint_position_right_elbow = geometry_msgs.msg.Point32()
      if self.joint_position_right_hand is None:
        self.joint_position_right_hand = geometry_msgs.msg.Point32()
      end = 0
      _x = self
      start = end
      end += 180
      (_x.body_id, _x.tracking_status, _x.gesture, _x.position2D.x, _x.position2D.y, _x.position2D.z, _x.centerOfMass.x, _x.centerOfMass.y, _x.centerOfMass.z, _x.joint_position_head.x, _x.joint_position_head.y, _x.joint_position_head.z, _x.joint_position_neck.x, _x.joint_position_neck.y, _x.joint_position_neck.z, _x.joint_position_shoulder.x, _x.joint_position_shoulder.y, _x.joint_position_shoulder.z, _x.joint_position_spine_top.x, _x.joint_position_spine_top.y, _x.joint_position_spine_top.z, _x.joint_position_spine_mid.x, _x.joint_position_spine_mid.y, _x.joint_position_spine_mid.z, _x.joint_position_spine_bottom.x, _x.joint_position_spine_bottom.y, _x.joint_position_spine_bottom.z, _x.joint_position_left_shoulder.x, _x.joint_position_left_shoulder.y, _x.joint_position_left_shoulder.z, _x.joint_position_left_elbow.x, _x.joint_position_left_elbow.y, _x.joint_position_left_elbow.z, _x.joint_position_left_hand.x, _x.joint_position_left_hand.y, _x.joint_position_left_hand.z, _x.joint_position_right_shoulder.x, _x.joint_position_right_shoulder.y, _x.joint_position_right_shoulder.z, _x.joint_position_right_elbow.x, _x.joint_position_right_elbow.y, _x.joint_position_right_elbow.z, _x.joint_position_right_hand.x, _x.joint_position_right_hand.y, _x.joint_position_right_hand.z,) = _get_struct_3i42f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3i42f = None
def _get_struct_3i42f():
    global _struct_3i42f
    if _struct_3i42f is None:
        _struct_3i42f = struct.Struct("<3i42f")
    return _struct_3i42f
